### ISSUE TITLE
AuthKEM traffic key computations mismatch

### ISSUE THREAD

**Issue by thomwiggers** [claucece/draft-celi-wiggers-tls-kemtls#30]
```
       [...]
SSc||0 * -> HKDF-Extract = Main Secret
            |
            +--> Derive-Secret(., "c ap traffic",
            |                  ClientHello...server Finished)
            |                  = client_application_traffic_secret_0
            |
            +--> Derive-Secret(., "s ap traffic",
            |                  ClientHello...server Finished)
            |                  = server_application_traffic_secret_0
[...]
```

The traffic keys are here shown to be derived from `server Finished`. This is not possible: we've not received/sent server's Finished yet when we already need to derive the client application traffic keys. The KEMTLS paper and analyses uses that these keys are derived from the *complete* transcript (unlike in TLS 1.3). Changing it to be derived from just client finished, I don't like so much.

**Comment by dstebila** [comment]
What's your concern about going up to just client finished?  There aren't any other messages between server finished and client finished, are there?

**Comment by thomwiggers** [comment]
I like the idea that the authentication status of the server is part of the key, which otherwise it would not be. It's also what we've analysed in Tamarin etcetera. I mainly don't see a good reason why to not include Server Finished

**Comment by dstebila** [comment]
I'm a bit confused. Back in the original KEMTLS paper we had the CATS derived from CH...CF and the SATS derived from CH...SF -- because those were the maximum extents of the transcript available at each point the value was derived.  Is that no longer the case?

**Comment by thomwiggers** [comment]
Yes, as quoted above, the AuthKEM draft currently states that they're derived from CH..SF which is what TLS 1.3 does

**Comment by thomwiggers** [comment]
I think this is simply copy and paste error
