### ISSUE TITLE
Move DC to appendix

### ISSUE THREAD

**Issue by thomwiggers** [claucece/draft-celi-wiggers-tls-kemtls#6]

**Comment by claucece** [comment]
The DC section is kinda separate from the draft right now and has no text, so we can easily move it. 

There is a section talking about a Certificate to deliver the public key (which could contain a  X509 cert or a raw public key): https://github.com/claucece/draft-celi-wiggers-tls-kemtls/blob/master/draft-celi-wiggers-tls-kemtls.md#certificate

Is there some other modifications you want there @chris-wood ?

**Comment by claucece** [comment]
Should be done now.
