### ISSUE TITLE
Is cached_info the right extension for conveying the public key?

### ISSUE THREAD

**Issue by chris-wood** [claucece/draft-celi-wiggers-tls-kemtls#9]
If we deliver the KEM public key via something that is not a certificate, should we use cached_info for conveying the public key digest/fingerprint?

**Comment by thomwiggers** [comment]
In the context of KEMTLS with predistributed keys, you kinda want to send `(key identifier, ciphertext)`, so a separate extension might just be better even for confusion reasons.

**Comment by claucece** [comment]
We don't use the cached_info extension as defined by rfc7924. We defined our own over here:

https://github.com/claucece/draft-celi-wiggers-tls-kemtls/blob/master/draft-celi-wiggers-tls-kemtls.md#cached-information

So, we can modify that paragraph to accept only the public key.

**Comment by thomwiggers** [comment]
we might want to avoid "cached_info" just to prevent any confusion...

**Comment by claucece** [comment]
Fixed now.
